services:
  # Servidor de Base de Datos Oracle
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db-container
    ports:
      - "1539:1521"
    environment:
      - ORACLE_PASSWORD=test1234
      - APP_USER=eric_dev
      - APP_USER_PASSWORD=test1234
    volumes:
      - ./database/init_db.sql:/container-entrypoint-initdb.d/init_db.sql
      - oracle-data:/opt/oracle/oradata

  #Servidor Web de Aplicaciones (Oracle Forms Services)
  forms-web:
    build: ./instaladores
    container_name: forms-web-container
    tty: true
    stdin_open: true
    ports:
      - "9001:9001"
    environment:
      - DB_CONNECT_STRING=oracle-db:1521/XEPDB1
      - DB_USER=eric_dev
      - DB_PASSWORD=test1234
    volumes:
      - ./forms-app:/u01/oracle/user_projects/domains/base_domain/config/forms
    depends_on:
      - oracle-db

volumes:
  oracle-data:
